metadata:
  name: "Hopper Engine CSJ v2"

geometry:
  nozzle_type: conical
  
  # Diameters (mm)
  chamber_diameter: 45.00
  throat_diameter: 16.00
  exit_diameter: 32.00

  # Lengths (mm)
  chamber_length: 107.59
  throat_length: 1.00
  
  # Radii and angles
  cyl_conv_radius: 5.00
  throat_conv_radius: 11.80
  throat_div_radius: 11.80
  converging_angle: 45.00
  diverging_angle: 15.00